### ISSUE TITLE
Spis komend potrzebnych do zrobienia ćwiczenia

### ISSUE THREAD

**Issue by kmorcinek** [kmorcinek/git-dev-warsztaty-presentation#21]
Gdy jest wytłumaczone ćwiczenie i czas na zrobienie to na rzutniku powinien być widoczne spis komend potrzebnych do zrobienia:
  * git co branch-name
  * git br
  * git reset --hard branch-name
  * git rebase master
  * git merge branch-name

**Comment by tometchy** [comment]
Pamiętać, żeby nie wydrukować z aliasami.

**Comment by tometchy** [comment]
Przełączniki do git log:
git log --after="2014-02-12T16:36:00-07:00"
git log --before="2014-02-12T16:36:00-07:00"
git log --since="1 month ago"
git log --since="2 weeks 3 days 2 hours 30 minutes 59 seconds ago"
git log -4
git log --oneline
git log --graph
git log --decorate
git log --stat
git log --patch
git log X --not Y, git log Y..X, git log X...Y
git log --author="xyz"
git log --grep="xyz"
git log --no-merges
git log --all

Przydaloby się chociaż jednym zdaniem je poopisywać

**Comment by tometchy** [comment]
Zwróć uwagę, żeby nie wydrukować z aliasami

**Comment by tometchy** [comment]
Nie trzeba drukować, wystarczy je umieścić w pliku cwiczenia.html - http://www.git-presentation.tk/cwiczenia

**Comment by kmorcinek** [comment]
Ok
